#
# Makefile for Broadcom bthid Driver
#

# Set KDIR to location of your kernel source
#KDIR := `pwd`/../kernel/msm

# Prebuilt toolchain directory
#PREBUILT := `pwd`/../prebuilt

# Set compiler toolchain
#CCOMPILER := $(PREBUILT)/linux-x86/toolchain/arm-eabi-4.4.0/bin/arm-eabi-

obj-m := bthid.o

#scsdio-y := bthid.o

#.PHONY: all clean

#all:
#	$(MAKE) -C $(KDIR) M=$(shell pwd) modules ARCH=arm CROSS_COMPILE=$(CCOMPILER)

#clean:
#	@rm -rf *~ .depend *.o .*.cmd *.ko *.mod.c .tmp_versions modules.order Module.symvers
