/*******************************************************************************
* Copyright 2010 Broadcom Corporation.  All rights reserved.
*
* 	@file	include/cfg_global.h
*
* Unless you and Broadcom execute a separate written software license agreement
* governing use of this software, this software is licensed to you under the
* terms of the GNU General Public License version 2, available at
* http://www.gnu.org/copyleft/gpl.html (the "GPL").
*
* Notwithstanding the above, under no circumstances may you combine this
* software in any way with any other Broadcom software provided under a license
* other than the GPL, without Broadcom's express prior written consent.
*******************************************************************************/

/* WARNING: Do not modify this file. */
/* This file is generated from config.mk */

#ifndef _CFG_GLOBAL_H_
#define _CFG_GLOBAL_H_

#include <linux/broadcom/cfg_global_defines.h>

/* Configuration from /opt/svn/2727B0/linux/target/configs/config.mk */
#undef CFG_GLOBAL_LINUX_VERSION
#undef CFG_GLOBAL_LINUX_BASE_VERSION
#undef CFG_GLOBAL_LINUX_PATCH_VERSION
#undef CFG_GLOBAL_ALSA_LIB_SUPPORT
#undef CFG_GLOBAL_ALSA_UTIL_SUPPORT
#undef CFG_GLOBAL_DLF_SUPPORT
#undef CFG_GLOBAL_ELFCMP_SUPPORT
#undef CFG_GLOBAL_IMGFIX_SUPPORT
#undef CFG_GLOBAL_SIGNED_IMAGE_UNSUPPORTED
#undef CFG_GLOBAL_SIGNED_IMAGE_NOKEY
#undef CFG_GLOBAL_SIGNED_IMAGE_512KEY
#undef CFG_GLOBAL_SIGNED_IMAGE_1024KEY
#undef CFG_GLOBAL_SIGNED_IMAGE_TYPE
#undef CFG_GLOBAL_MICROWIN_SUPPORT
#undef CFG_GLOBAL_MICROWIN_SCREEN_PIXTYPE
#undef CFG_GLOBAL_OTAIMAGE_SUPPORT
#undef CFG_GLOBAL_SWIG_SUPPORT
#undef CFG_GLOBAL_TCL_SUPPORT
#undef CFG_GLOBAL_VC02_SUPPORT
#undef CFG_GLOBAL_VC03_SUPPORT
#undef CFG_GLOBAL_VC03_B0_SUPPORT
#undef CFG_GLOBAL_GFX_SERVICE_SUPPORT
#undef CFG_GLOBAL_VIDEO_BOOT_FROM_KERNEL
#undef CFG_GLOBAL_XML_SUPPORT
#undef CFG_GLOBAL_STDCPP_SUPPORT
#undef CFG_GLOBAL_UBI_SUPPORT
#undef CFG_GLOBAL_BRCM_BOOT0_SUPPORT
#undef CFG_GLOBAL_BRCM_BOOT12_SUPPORT
#undef CFG_GLOBAL_U_BOOT_SUPPORT
#undef CFG_GLOBAL_U_BOOT_VERSION
#undef CFG_GLOBAL_U_BOOT_OVERRIDE
#undef CFG_GLOBAL_BOOT_NAND_FLASH
#undef CFG_GLOBAL_NAND_ERASESIZE
#undef CFG_GLOBAL_FLASH_SIZE_MB
#undef CFG_GLOBAL_BUSYBOX_SUPPORT
#undef CFG_GLOBAL_BUILD_BUSYBOX_SUPPORT
#undef CFG_GLOBAL_BUSYBOX_VERSION
#undef CFG_GLOBAL_CAMCTL_SUPPORT
#undef CFG_GLOBAL_DEBUG_TEST_SUPPORT
#undef CFG_GLOBAL_DRIVER_TEST_SUPPORT
#undef CFG_GLOBAL_FLASH_TEST_SUPPORT
#undef CFG_GLOBAL_GPIO_SUPPORT
#undef CFG_GLOBAL_HELLO_WORLD_SUPPORT
#undef CFG_GLOBAL_HWCLOCK_SUPPORT
#undef CFG_GLOBAL_I2C_SUPPORT
#undef CFG_GLOBAL_OTP_SUPPORT
#undef CFG_GLOBAL_BACKLIGHT_SUPPORT
#undef CFG_GLOBAL_BLCTL_SUPPORT
#undef CFG_GLOBAL_IOCMD_SUPPORT
#undef CFG_GLOBAL_GREYBOX_SUPPORT
#undef CFG_GLOBAL_INPUT_SUPPORT
#undef CFG_GLOBAL_LCDCTL_SUPPORT
#undef CFG_GLOBAL_FBCTL_SUPPORT
#undef CFG_GLOBAL_SETSCHED_SUPPORT
#undef CFG_GLOBAL_PMU_TEST_SUPPORT
#undef CFG_GLOBAL_PHP_SUPPORT
#undef CFG_GLOBAL_SERIAL_TEST_SUPPORT
#undef CFG_GLOBAL_SHOW_SUPPORT
#undef CFG_GLOBAL_SIM_SUPPORT
#undef CFG_GLOBAL_UDP_TEST_SUPPORT
#undef CFG_GLOBAL_TCP_TEST_SUPPORT
#undef CFG_GLOBAL_VIDEO_TEST_SUPPORT
#undef CFG_GLOBAL_ETH_TEST_SUPPORT
#undef CFG_GLOBAL_IGMP_TEST_SUPPORT
#undef CFG_GLOBAL_PTHREAD_BASIC_TEST_SUPPORT
#undef CFG_GLOBAL_PTHREAD_COND_WAIT_TEST_SUPPORT
#undef CFG_GLOBAL_SYSLOG_TEST_SUPPORT
#undef CFG_GLOBAL_WATCHDOGD_SUPPORT
#undef CFG_GLOBAL_GDB_SERVER_SUPPORT
#undef CFG_GLOBAL_GDB_SUPPORT
#undef CFG_GLOBAL_ETHTOOL_SUPPORT
#undef CFG_GLOBAL_JPEG_SUPPORT
#undef CFG_GLOBAL_LRZSZ_SUPPORT
#undef CFG_GLOBAL_NTP_SUPPORT
#undef CFG_GLOBAL_OPENSSL_SUPPORT
#undef CFG_GLOBAL_OPENSSL_TEST_CORE
#undef CFG_GLOBAL_OPENSSL_TEST
#undef CFG_GLOBAL_PTH_SUPPORT
#undef CFG_GLOBAL_LIBRT_SUPPORT
#undef CFG_GLOBAL_TCPDUMP_SUPPORT
#undef CFG_GLOBAL_STRACE_SUPPORT
#undef CFG_GLOBAL_SOCAT_SUPPORT
#undef CFG_GLOBAL_FFMPEG_SUPPORT
#undef CFG_GLOBAL_PKA_SUPPORT
#undef CFG_GLOBAL_GEV3_CMODEL_SUPPORT
#undef CFG_GLOBAL_APM_TEST_SUPPORT
#undef CFG_GLOBAL_SPU_TEST_SUPPORT
#undef CFG_GLOBAL_PKA_TEST_SUPPORT
#undef CFG_GLOBAL_SROMPROG_SUPPORT
#undef CFG_GLOBAL_WLDRIVER_SUPPORT
#undef CFG_GLOBAL_DHD_SUPPORT
#undef CFG_GLOBAL_OTA_ENABLE
#undef CFG_GLOBAL_OTA_CGI_ENABLE
#undef CFG_GLOBAL_SAMBA_SERVER_SUPPORT
#undef CFG_GLOBAL_SAMBA_CLIENT_SUPPORT
#undef CFG_GLOBAL_NFS_CLIENT_SUPPORT
#undef CFG_GLOBAL_KSZ8842_SUPPORT
#undef CFG_GLOBAL_MTDUTIL_SUPPORT
#undef CFG_GLOBAL_SQLITE3_SUPPORT
#undef CFG_GLOBAL_RAM_SIZE
#undef CFG_GLOBAL_RAM_RESERVED_SIZE
#undef CFG_GLOBAL_RAM_BASE
#undef CFG_GLOBAL_HALAUDIO_SUPPORT
#undef CFG_GLOBAL_EEMBC_NET_SUPPORT
#undef CFG_GLOBAL_EEMBC_DEN_SUPPORT
#undef CFG_GLOBAL_EEMBC_JAVA_SUPPORT
#undef CFG_GLOBAL_JAVA_SUPPORT
#undef CFG_GLOBAL_BTE_SUPPORT
#undef CFG_GLOBAL_PRIV_WMDRM_SUPPORT
#undef CFG_GLOBAL_WIRED_ENET_SUPPORT
#undef CFG_GLOBAL_TOUCHSCREEN_SUPPORT
#undef CFG_GLOBAL_RTLSIM_SUPPORT
#undef CFG_GLOBAL_VDEC_SUPPORT
#undef CFG_GLOBAL_VC03_B0_MPHI_MINI
#undef CFG_GLOBAL_VPMSCALED_SUPPORT
#undef CFG_GLOBAL_VPMINTSTRESS_SUPPORT
#undef CFG_GLOBAL_VDEC_TOOL_SUPPORT
#undef CFG_GLOBAL_PERFTEST_SUPPORT
#undef CFG_GLOBAL_PTH_SUPPORT
#undef CFG_GLOBAL_ECLIPSE_DBG_SUPPORT
#undef CFG_GLOBAL_KERNEL_DEBUG_SUPPORT
#undef CFG_GLOBAL_ROOT_FILE_SYSTEM
#undef CFG_GLOBAL_FILE_SYSTEM_JFFS2
#undef CFG_GLOBAL_FILE_SYSTEM_CRAMFS
#undef CFG_GLOBAL_FILE_SYSTEM_INITRAMFS
#undef CFG_GLOBAL_UIMAGE_SUPPORT
#undef CFG_GLOBAL_PAD_ROOTFS_SIZE
#undef CFG_GLOBAL_GROOVE_DOWNLOAD_TOOL_LE
#undef CFG_GLOBAL_GROOVE_FIRMWARE_VER
#undef CFG_GLOBAL_BCM_FUSE_APPS_PROCESSOR
#undef CFG_GLOBAL_BCM282X_NAND
#undef CFG_GLOBAL_XML_SUPPORT
#undef CFG_GLOBAL_CURL_SUPPORT
#undef CFG_GLOBAL_LIBICONV_SUPPORT
#undef CFG_GLOBAL_GETTEXT_SUPPORT
#undef CFG_GLOBAL_GLIB_SUPPORT
#undef CFG_GLOBAL_ZLIB_SUPPORT
#undef CFG_GLOBAL_FREETYPE_SUPPORT
#undef CFG_GLOBAL_LIBXML2_SUPPORT
#undef CFG_GLOBAL_FONTCONFIG_SUPPORT
#undef CFG_GLOBAL_ATK_SUPPORT
#undef CFG_GLOBAL_LIBPNG_SUPPORT
#undef CFG_GLOBAL_DIRECTFB_SUPPORT
#undef CFG_GLOBAL_DIRECTFB_EXAMPLES_SUPPORT
#undef CFG_GLOBAL_CAIRO_SUPPORT
#undef CFG_GLOBAL_PANGO_SUPPORT
#undef CFG_GLOBAL_GTK_SUPPORT
#undef CFG_GLOBAL_READLINE_SUPPORT
#undef CFG_GLOBAL_SQLITE_SUPPORT
#undef CFG_GLOBAL_LIBGPG_EEROR_SUPPORT
#undef CFG_GLOBAL_LIBGCRYPT_SUPPORT
#undef CFG_GLOBAL_LIBXSLT_SUPPORT
#undef CFG_GLOBAL_ICU_SUPPORT
#undef CFG_GLOBAL_WEBKIT_SUPPORT
#undef CFG_GLOBAL_CHIP_FAMILY
#undef CFG_GLOBAL_TOOLCHAIN_VERSION
#undef CFG_GLOBAL_IPV6_SUPPORT
#undef CFG_GLOBAL_EMQBIT_BENCH_SUPPORT
#define CFG_GLOBAL_LINUX_VERSION   "linux-2.6.27"
#define CFG_GLOBAL_LINUX_BASE_VERSION
#define CFG_GLOBAL_LINUX_PATCH_VERSION
#define CFG_GLOBAL_ALSA_LIB_SUPPORT   1
#define CFG_GLOBAL_ALSA_UTIL_SUPPORT   1
#define CFG_GLOBAL_DLF_SUPPORT   1
#define CFG_GLOBAL_ELFCMP_SUPPORT   1
#define CFG_GLOBAL_IMGFIX_SUPPORT   1
#define CFG_GLOBAL_SIGNED_IMAGE_UNSUPPORTED   0
#define CFG_GLOBAL_SIGNED_IMAGE_NOKEY   0x80
#define CFG_GLOBAL_SIGNED_IMAGE_512KEY   0x20
#define CFG_GLOBAL_SIGNED_IMAGE_1024KEY   0x30
#define CFG_GLOBAL_SIGNED_IMAGE_TYPE   0
#define CFG_GLOBAL_MICROWIN_SUPPORT   1
#define CFG_GLOBAL_MICROWIN_SCREEN_PIXTYPE   MWPF_TRUECOLOR565
#define CFG_GLOBAL_OTAIMAGE_SUPPORT   1
#define CFG_GLOBAL_SWIG_SUPPORT   0
#define CFG_GLOBAL_TCL_SUPPORT   0
#define CFG_GLOBAL_VC02_SUPPORT   0
#define CFG_GLOBAL_VC03_SUPPORT   0
#define CFG_GLOBAL_VC03_B0_SUPPORT   0
#define CFG_GLOBAL_GFX_SERVICE_SUPPORT   0
#define CFG_GLOBAL_VIDEO_BOOT_FROM_KERNEL   0
#define CFG_GLOBAL_XML_SUPPORT   0
#define CFG_GLOBAL_STDCPP_SUPPORT   0
#define CFG_GLOBAL_UBI_SUPPORT   0
#define CFG_GLOBAL_BRCM_BOOT0_SUPPORT   0
#define CFG_GLOBAL_BRCM_BOOT12_SUPPORT   1
#define CFG_GLOBAL_U_BOOT_SUPPORT   0
#define CFG_GLOBAL_U_BOOT_VERSION   "u-boot-1.3.3"
#define CFG_GLOBAL_U_BOOT_OVERRIDE   0
#define CFG_GLOBAL_BOOT_NAND_FLASH   1	/* default to boot from NAND flash */
#define CFG_GLOBAL_NAND_ERASESIZE   0x4000
#define CFG_GLOBAL_FLASH_SIZE_MB   32
#define CFG_GLOBAL_BUSYBOX_SUPPORT   1
#define CFG_GLOBAL_BUILD_BUSYBOX_SUPPORT   0
#define CFG_GLOBAL_BUSYBOX_VERSION   "busybox-1.01"
#define CFG_GLOBAL_CAMCTL_SUPPORT   1
#define CFG_GLOBAL_DEBUG_TEST_SUPPORT   1
#define CFG_GLOBAL_DRIVER_TEST_SUPPORT   1
#define CFG_GLOBAL_FLASH_TEST_SUPPORT   1
#define CFG_GLOBAL_GPIO_SUPPORT   1
#define CFG_GLOBAL_HELLO_WORLD_SUPPORT   1
#define CFG_GLOBAL_HWCLOCK_SUPPORT   1
#define CFG_GLOBAL_I2C_SUPPORT   0
#define CFG_GLOBAL_OTP_SUPPORT   0
#define CFG_GLOBAL_BACKLIGHT_SUPPORT   1
#define CFG_GLOBAL_BLCTL_SUPPORT   1
#define CFG_GLOBAL_IOCMD_SUPPORT   1
#define CFG_GLOBAL_GREYBOX_SUPPORT   1
#define CFG_GLOBAL_INPUT_SUPPORT   1
#define CFG_GLOBAL_LCDCTL_SUPPORT   1
#define CFG_GLOBAL_FBCTL_SUPPORT   0
#define CFG_GLOBAL_SETSCHED_SUPPORT   1
#define CFG_GLOBAL_PMU_TEST_SUPPORT   1
#define CFG_GLOBAL_PHP_SUPPORT   0
#define CFG_GLOBAL_SERIAL_TEST_SUPPORT   1
#define CFG_GLOBAL_SHOW_SUPPORT   1
#define CFG_GLOBAL_SIM_SUPPORT   0
#define CFG_GLOBAL_UDP_TEST_SUPPORT   1
#define CFG_GLOBAL_TCP_TEST_SUPPORT   0
#define CFG_GLOBAL_VIDEO_TEST_SUPPORT   0
#define CFG_GLOBAL_ETH_TEST_SUPPORT   0
#define CFG_GLOBAL_IGMP_TEST_SUPPORT   0
#define CFG_GLOBAL_PTHREAD_BASIC_TEST_SUPPORT   0
#define CFG_GLOBAL_PTHREAD_COND_WAIT_TEST_SUPPORT   0
#define CFG_GLOBAL_SYSLOG_TEST_SUPPORT   0
#define CFG_GLOBAL_WATCHDOGD_SUPPORT   1
#define CFG_GLOBAL_GDB_SERVER_SUPPORT   1
#define CFG_GLOBAL_GDB_SUPPORT   0
#define CFG_GLOBAL_ETHTOOL_SUPPORT   0
#define CFG_GLOBAL_JPEG_SUPPORT   1
#define CFG_GLOBAL_LRZSZ_SUPPORT   1
#define CFG_GLOBAL_NTP_SUPPORT   1
#define CFG_GLOBAL_OPENSSL_SUPPORT   0
#define CFG_GLOBAL_OPENSSL_TEST_CORE   0
#define CFG_GLOBAL_OPENSSL_TEST   0
#define CFG_GLOBAL_PTH_SUPPORT   0
#define CFG_GLOBAL_LIBRT_SUPPORT   0
#define CFG_GLOBAL_TCPDUMP_SUPPORT   1
#define CFG_GLOBAL_STRACE_SUPPORT   0
#define CFG_GLOBAL_SOCAT_SUPPORT   1
#define CFG_GLOBAL_FFMPEG_SUPPORT   0
#define CFG_GLOBAL_PKA_SUPPORT   0
#define CFG_GLOBAL_GEV3_CMODEL_SUPPORT   0
#define CFG_GLOBAL_APM_TEST_SUPPORT   0
#define CFG_GLOBAL_SPU_TEST_SUPPORT   0
#define CFG_GLOBAL_PKA_TEST_SUPPORT   0
#define CFG_GLOBAL_SROMPROG_SUPPORT   0
#define CFG_GLOBAL_WLDRIVER_SUPPORT   0
#define CFG_GLOBAL_DHD_SUPPORT   0
#define CFG_GLOBAL_OTA_ENABLE   1
#define CFG_GLOBAL_OTA_CGI_ENABLE   0
#define CFG_GLOBAL_SAMBA_SERVER_SUPPORT   0
#define CFG_GLOBAL_SAMBA_CLIENT_SUPPORT   0
#define CFG_GLOBAL_NFS_CLIENT_SUPPORT   1
#define CFG_GLOBAL_KSZ8842_SUPPORT   0
#define CFG_GLOBAL_MTDUTIL_SUPPORT   0
#define CFG_GLOBAL_SQLITE3_SUPPORT   0
#define CFG_GLOBAL_RAM_SIZE   0x6000000
#define CFG_GLOBAL_RAM_RESERVED_SIZE   0x400000
#define CFG_GLOBAL_RAM_BASE   0x80000000
#define CFG_GLOBAL_HALAUDIO_SUPPORT   0
#define CFG_GLOBAL_EEMBC_NET_SUPPORT   0
#define CFG_GLOBAL_EEMBC_DEN_SUPPORT   0
#define CFG_GLOBAL_EEMBC_JAVA_SUPPORT   0
#define CFG_GLOBAL_JAVA_SUPPORT   0
#define CFG_GLOBAL_BTE_SUPPORT   0
#define CFG_GLOBAL_PRIV_WMDRM_SUPPORT   0
#define CFG_GLOBAL_WIRED_ENET_SUPPORT   0
#define CFG_GLOBAL_TOUCHSCREEN_SUPPORT   0
#define CFG_GLOBAL_RTLSIM_SUPPORT   0
#define CFG_GLOBAL_VDEC_SUPPORT   0
#define CFG_GLOBAL_VC03_B0_MPHI_MINI   0
#define CFG_GLOBAL_VPMSCALED_SUPPORT   0
#define CFG_GLOBAL_VPMINTSTRESS_SUPPORT   0
#define CFG_GLOBAL_VDEC_TOOL_SUPPORT   0
#define CFG_GLOBAL_PERFTEST_SUPPORT   0
#define CFG_GLOBAL_PTH_SUPPORT   0
#define CFG_GLOBAL_ECLIPSE_DBG_SUPPORT   0
#define CFG_GLOBAL_KERNEL_DEBUG_SUPPORT   0
#define CFG_GLOBAL_ROOT_FILE_SYSTEM   JFFS2_RFS
#define CFG_GLOBAL_FILE_SYSTEM_JFFS2   1
#define CFG_GLOBAL_FILE_SYSTEM_CRAMFS   1
#define CFG_GLOBAL_FILE_SYSTEM_INITRAMFS   0
#define CFG_GLOBAL_UIMAGE_SUPPORT   0
#define CFG_GLOBAL_PAD_ROOTFS_SIZE   0
#define CFG_GLOBAL_GROOVE_DOWNLOAD_TOOL_LE   0
#define CFG_GLOBAL_GROOVE_FIRMWARE_VER   1.2.17
#define CFG_GLOBAL_BCM_FUSE_APPS_PROCESSOR   0
#define CFG_GLOBAL_BCM282X_NAND   0
#define CFG_GLOBAL_XML_SUPPORT   0
#define CFG_GLOBAL_CURL_SUPPORT   0
#define CFG_GLOBAL_LIBICONV_SUPPORT   0
#define CFG_GLOBAL_GETTEXT_SUPPORT   0
#define CFG_GLOBAL_GLIB_SUPPORT   0
#define CFG_GLOBAL_ZLIB_SUPPORT   0
#define CFG_GLOBAL_FREETYPE_SUPPORT   0
#define CFG_GLOBAL_LIBXML2_SUPPORT   0
#define CFG_GLOBAL_FONTCONFIG_SUPPORT   0
#define CFG_GLOBAL_ATK_SUPPORT   0
#define CFG_GLOBAL_LIBPNG_SUPPORT   0
#define CFG_GLOBAL_DIRECTFB_SUPPORT   0
#define CFG_GLOBAL_DIRECTFB_EXAMPLES_SUPPORT   0
#define CFG_GLOBAL_CAIRO_SUPPORT   0
#define CFG_GLOBAL_PANGO_SUPPORT   0
#define CFG_GLOBAL_GTK_SUPPORT   0
#define CFG_GLOBAL_READLINE_SUPPORT   0
#define CFG_GLOBAL_SQLITE_SUPPORT   0
#define CFG_GLOBAL_LIBGPG_EEROR_SUPPORT   0
#define CFG_GLOBAL_LIBGCRYPT_SUPPORT   0
#define CFG_GLOBAL_LIBXSLT_SUPPORT   0
#define CFG_GLOBAL_ICU_SUPPORT   0
#define CFG_GLOBAL_WEBKIT_SUPPORT   0
#define CFG_GLOBAL_CHIP_FAMILY   CFG_GLOBAL_CHIP_FAMILY_NONE
#define CFG_GLOBAL_TOOLCHAIN_VERSION   "buildroot-20060918"
#define CFG_GLOBAL_IPV6_SUPPORT   0
#define CFG_GLOBAL_EMQBIT_BENCH_SUPPORT   0

/* Configuration from /opt/svn/2727B0/linux/target/configs/BCM2153/config.mk */
#undef CFG_GLOBAL_CHIP
#undef CFG_GLOBAL_CPU
#undef CFG_GLOBAL_CPU_ENDIAN
#undef CFG_GLOBAL_CHIP_FAMILY
#undef CFG_GLOBAL_BCM116X_TYPE
#undef CFG_GLOBAL_DLF_SUPPORT
#undef CFG_GLOBAL_BRCM_BOOT12_SUPPORT
#undef CFG_GLOBAL_UBI_SUPPORT
#undef CFG_GLOBAL_PAD_ROOTFS_SIZE
#define CFG_GLOBAL_CHIP                         BCM2153
#define CFG_GLOBAL_CPU                          ARM11
#define CFG_GLOBAL_CPU_ENDIAN                   le
#define CFG_GLOBAL_CHIP_FAMILY                  CFG_GLOBAL_CHIP_FAMILY_BCM116X
#define CFG_GLOBAL_BCM116X_TYPE                 CFG_GLOBAL_BCM2153
#define CFG_GLOBAL_DLF_SUPPORT                  1
#define CFG_GLOBAL_BRCM_BOOT12_SUPPORT          1
#define CFG_GLOBAL_UBI_SUPPORT          1
#define CFG_GLOBAL_PAD_ROOTFS_SIZE   0x2800000

/* Configuration from /opt/svn/2727B0/linux/boards/BCM9_VESPER/config.mk */
#undef CFG_GLOBAL_HALAUDIO_SUPPORT
#undef CFG_GLOBAL_I2C_SUPPORT
#undef CFG_GLOBAL_MICROWIN_SUPPORT
#undef CFG_GLOBAL_SHOW_SUPPORT
#undef CFG_GLOBAL_ALSA_LIB_SUPPORT
#undef CFG_GLOBAL_ALSA_UTIL_SUPPORT
#undef CFG_GLOBAL_DHD_SUPPORT
#undef CFG_GLOBAL_LCDCTL_SUPPORT
#undef CFG_GLOBAL_ROOT_FILE_SYSTEM
#undef CFG_GLOBAL_WATCHDOGD_SUPPORT
#undef CFG_GLOBAL_XML_SUPPORT
#undef CFG_GLOBAL_LIBICONV_SUPPORT
#undef CFG_GLOBAL_GETTEXT_SUPPORT
#undef CFG_GLOBAL_GLIB_SUPPORT
#undef CFG_GLOBAL_ZLIB_SUPPORT
#undef CFG_GLOBAL_FREETYPE_SUPPORT
#undef CFG_GLOBAL_LIBXML2_SUPPORT
#undef CFG_GLOBAL_FONTCONFIG_SUPPORT
#undef CFG_GLOBAL_ATK_SUPPORT
#undef CFG_GLOBAL_LIBPNG_SUPPORT
#undef CFG_GLOBAL_JPEG_SUPPORT
#undef CFG_GLOBAL_DIRECTFB_SUPPORT
#undef CFG_GLOBAL_DIRECTFB_EXAMPLES_SUPPORT
#undef CFG_GLOBAL_CAIRO_SUPPORT
#undef CFG_GLOBAL_PANGO_SUPPORT
#undef CFG_GLOBAL_GTK_SUPPORT
#undef CFG_GLOBAL_VC03
#undef CFG_GLOBAL_VC03_SUPPORT
#undef CFG_GLOBAL_VC03_UMI
#undef CFG_GLOBAL_OMX_SUPPORT
#undef CFG_GLOBAL_OMXCTL_SUPPORT
#undef CFG_GLOBAL_OMX_CLIENT_SUPPORT
#undef CFG_GLOBAL_MEDIA_PARSERS_SUPPORT
#undef CFG_GLOBAL_MSG_QUEUE
#undef CFG_GLOBAL_MEDIA_HANDLERS
#undef CFG_GLOBAL_OMX_HOST_COMPONENTS
#undef CFG_GLOBAL_GROOVE_WINDOWS_DOWNLOAD
#undef CFG_GLOBAL_GROOVE_DOWNLOAD_TOOL_LE
#undef CFG_GLOBAL_GROOVE_FIRMWARE_VER
#undef CFG_GLOBAL_BCM_FUSE_APPS_PROCESSOR
#undef CFG_GLOBAL_RAM_BASE
#undef CFG_GLOBAL_BCM_FUSE_TELD_SUPPORT
#undef CFG_GLOBAL_BCM_FUSE_CAPI2_SUPPORT
#undef CFG_GLOBAL_BCM_FUSE_IPC_SUPPORT
#undef CFG_GLOBAL_LOG_SUPPORT
#undef CFG_GLOBAL_CPLOG_SUPPORT
#undef CFG_GLOBAL_BCM_FUSE_APPS_IMG_ZIP_FILE
#undef CFG_GLOBAL_BCM_FUSE_COMMS_IMG_ZIP_FILE
#undef CFG_GLOBAL_BCM_FUSE_BAT_FILE
#undef CFG_GLOBAL_BCM_FUSE_USB_BAT_FILE
#undef CFG_GLOBAL_BCM_FUSE_PATCH_FILE
#undef CFG_GLOBAL_BCM_VMCS_ROOTFS
#undef CFG_GLOBAL_BCM_VMCS_REL_FILES
#undef CFG_GLOBAL_UIMAGE_SUPPORT
#undef CFG_GLOBAL_U_BOOT_SUPPORT
#undef CFG_GLOBAL_PAD_ROOTFS_SIZE
#define CFG_GLOBAL_HALAUDIO_SUPPORT             0
#define CFG_GLOBAL_I2C_SUPPORT                  1
#define CFG_GLOBAL_MICROWIN_SUPPORT             0
#define CFG_GLOBAL_SHOW_SUPPORT                 0
#define CFG_GLOBAL_ALSA_LIB_SUPPORT             1
#define CFG_GLOBAL_ALSA_UTIL_SUPPORT            1
#define CFG_GLOBAL_DHD_SUPPORT   1
#define CFG_GLOBAL_LCDCTL_SUPPORT                1
#define CFG_GLOBAL_ROOT_FILE_SYSTEM   JFFS2_RFS
#define CFG_GLOBAL_WATCHDOGD_SUPPORT   1
#define CFG_GLOBAL_XML_SUPPORT   1
#define CFG_GLOBAL_LIBICONV_SUPPORT   1
#define CFG_GLOBAL_GETTEXT_SUPPORT   1
#define CFG_GLOBAL_GLIB_SUPPORT   1
#define CFG_GLOBAL_ZLIB_SUPPORT   1
#define CFG_GLOBAL_FREETYPE_SUPPORT   1
#define CFG_GLOBAL_LIBXML2_SUPPORT   1
#define CFG_GLOBAL_FONTCONFIG_SUPPORT   1
#define CFG_GLOBAL_ATK_SUPPORT   1
#define CFG_GLOBAL_LIBPNG_SUPPORT   1
#define CFG_GLOBAL_JPEG_SUPPORT   1
#define CFG_GLOBAL_DIRECTFB_SUPPORT   1
#define CFG_GLOBAL_DIRECTFB_EXAMPLES_SUPPORT   1
#define CFG_GLOBAL_CAIRO_SUPPORT   1
#define CFG_GLOBAL_PANGO_SUPPORT   1
#define CFG_GLOBAL_GTK_SUPPORT   1
#define CFG_GLOBAL_VC03                          1
#define CFG_GLOBAL_VC03_SUPPORT                  1
#define CFG_GLOBAL_VC03_UMI                      1
#define CFG_GLOBAL_OMX_SUPPORT                   1
#define CFG_GLOBAL_OMXCTL_SUPPORT                1
#define CFG_GLOBAL_OMX_CLIENT_SUPPORT            1
#define CFG_GLOBAL_MEDIA_PARSERS_SUPPORT   1
#define CFG_GLOBAL_MSG_QUEUE   1
#define CFG_GLOBAL_MEDIA_HANDLERS   1
#define CFG_GLOBAL_OMX_HOST_COMPONENTS   1
#define CFG_GLOBAL_GROOVE_WINDOWS_DOWNLOAD  1
#define CFG_GLOBAL_GROOVE_DOWNLOAD_TOOL_LE   1
#define CFG_GLOBAL_GROOVE_FIRMWARE_VER   1.2.17
#define CFG_GLOBAL_BCM_FUSE_APPS_PROCESSOR   1
#define CFG_GLOBAL_RAM_BASE   0x82000000
#define CFG_GLOBAL_BCM_FUSE_TELD_SUPPORT   1
#define CFG_GLOBAL_BCM_FUSE_CAPI2_SUPPORT   1
#define CFG_GLOBAL_BCM_FUSE_IPC_SUPPORT   1
#define CFG_GLOBAL_LOG_SUPPORT   1
#define CFG_GLOBAL_CPLOG_SUPPORT   1
#define CFG_GLOBAL_BCM_FUSE_APPS_IMG_ZIP_FILE   "groove/Torpedoray/release_1.2.17/Release Package/TORPEDORAY_APPS_PLUS_D0_59035B0.zip"
#define CFG_GLOBAL_BCM_FUSE_COMMS_IMG_ZIP_FILE   "groove/Torpedoray/release_1.2.17/Release Package/COMMS_VESPER_HEDGE_EP2.zip"
#define CFG_GLOBAL_BCM_FUSE_BAT_FILE   torpedoray.bat
#define CFG_GLOBAL_BCM_FUSE_USB_BAT_FILE   martini_usb.bat
#define CFG_GLOBAL_BCM_FUSE_PATCH_FILE   0060_vesper.patch
#define CFG_GLOBAL_BCM_VMCS_ROOTFS   1
#define CFG_GLOBAL_BCM_VMCS_REL_FILES   "vmcs/BCM9_VESPER_BCM2153C0/release_0_6/vc03"
#define CFG_GLOBAL_UIMAGE_SUPPORT   1
#define CFG_GLOBAL_U_BOOT_SUPPORT   1
#define CFG_GLOBAL_PAD_ROOTFS_SIZE   0

/* Configuration from /opt/svn/2727B0/linux/boards/BCM9_VESPER_EP3_WVGA/config.mk */
#undef CFG_GLOBAL_FLASH_SIZE_MB
#undef CFG_GLOBAL_GFX_SERVICE_SUPPORT
#undef CFG_GLOBAL_GLCLEAR_TEST_SUPPORT
#undef CFG_GLOBAL_DISPMAN_SUPPORT
#undef CFG_GLOBAL_DISPMAN_TEST_SUPPORT
#undef CFG_GLOBAL_OPENVG_TEST_SUPPORT
#undef CFG_GLOBAL_ROLLER_DEMO_SUPPORT
#undef CFG_GLOBAL_TIGER_DEMO_SUPPORT
#undef CFG_GLOBAL_BCM4325_APP_SUPPORT
#undef CFG_GLOBAL_VC03B0
#undef CFG_GLOBAL_VC03_SMIB0
#undef CFG_GLOBAL_OMX_SUPPORT
#undef CFG_GLOBAL_OMXCTL_SUPPORT
#undef CFG_GLOBAL_OMX_CLIENT_SUPPORT
#undef CFG_GLOBAL_BCM_VMCS_ROOTFS
#undef CFG_GLOBAL_BCM_VMCS_REL_FILES
#define CFG_GLOBAL_FLASH_SIZE_MB		        128
#define CFG_GLOBAL_GFX_SERVICE_SUPPORT           1	/* kernel support for Khronos graphics APIs (VC3 only) */
#define CFG_GLOBAL_GLCLEAR_TEST_SUPPORT          1
#define CFG_GLOBAL_DISPMAN_SUPPORT               0
#define CFG_GLOBAL_DISPMAN_TEST_SUPPORT          0
#define CFG_GLOBAL_OPENVG_TEST_SUPPORT           0
#define CFG_GLOBAL_ROLLER_DEMO_SUPPORT           1
#define CFG_GLOBAL_TIGER_DEMO_SUPPORT            1
#define CFG_GLOBAL_BCM4325_APP_SUPPORT           1
#define CFG_GLOBAL_VC03B0                        1
#define CFG_GLOBAL_VC03_SMIB0                    1
#define CFG_GLOBAL_OMX_SUPPORT                   1
#define CFG_GLOBAL_OMXCTL_SUPPORT                1
#define CFG_GLOBAL_OMX_CLIENT_SUPPORT            1
#define CFG_GLOBAL_BCM_VMCS_ROOTFS   1
#define CFG_GLOBAL_BCM_VMCS_REL_FILES   "vmcs/BCM9_VESPER_EP3_WVGA/vc03"

/* Configuration from /opt/svn/2727B0/sample-app/build/config.mk */
#undef CFG_GLOBAL_TEST_LIB_SUPPORT
#undef CFG_GLOBAL_TEST_APP_SUPPORT
#undef CFG_GLOBAL_PRIV_LIB1_SUPPORT
#undef CFG_GLOBAL_PRIV_APP1_SUPPORT
#undef CFG_GLOBAL_DRIVER_TEST_SUPPORT
#undef CFG_GLOBAL_SERIAL_TEST_SUPPORT
#undef CFG_GLOBAL_DEBUG_TEST_SUPPORT
#define CFG_GLOBAL_TEST_LIB_SUPPORT   0
#define CFG_GLOBAL_TEST_APP_SUPPORT   0
#define CFG_GLOBAL_PRIV_LIB1_SUPPORT   0
#define CFG_GLOBAL_PRIV_APP1_SUPPORT   0
#define CFG_GLOBAL_DRIVER_TEST_SUPPORT   1
#define CFG_GLOBAL_SERIAL_TEST_SUPPORT   1
#define CFG_GLOBAL_DEBUG_TEST_SUPPORT   1

/* Configuration from /opt/svn/2727B0/sample-app/build/boards/BCM9_VESPER_EP3_WVGA/config.mk */

/* Configuration from /opt/svn/2727B0/sample-app/build/aptest/custom/config.mk */
#undef CFG_GLOBAL_LMBENCH_SUPPORT
#undef CFG_GLOBAL_KERNEL_DEBUG_SUPPORT
#undef CFG_GLOBAL_BRCM_BOOT12_SUPPORT
#undef CFG_GLOBAL_MICROWIN_SUPPORT
#undef CFG_GLOBAL_SHOW_SUPPORT
#undef CFG_GLOBAL_OTA_ENABLE
#undef CFG_GLOBAL_TCPDUMP_SUPPORT
#undef CFG_GLOBAL_SOCAT_SUPPORT
#undef CFG_GLOBAL_STRACE_SUPPORT
#undef CFG_GLOBAL_NTP_SUPPORT
#undef CFG_GLOBAL_ETHTOOL_SUPPORT
#undef CFG_GLOBAL_LIBRT_SUPPORT
#undef CFG_GLOBAL_OPENSSL_SUPPORT
#undef CFG_GLOBAL_SROMPROG_SUPPORT
#undef CFG_GLOBAL_WLDRIVER_SUPPORT
#undef CFG_GLOBAL_DHD_SUPPORT
#undef CFG_GLOBAL_TOOLCHAIN_VERSION
#define CFG_GLOBAL_LMBENCH_SUPPORT   1
#define CFG_GLOBAL_KERNEL_DEBUG_SUPPORT         0
#define CFG_GLOBAL_BRCM_BOOT12_SUPPORT          0
#define CFG_GLOBAL_MICROWIN_SUPPORT             0
#define CFG_GLOBAL_SHOW_SUPPORT                 0
#define CFG_GLOBAL_OTA_ENABLE                   0
#define CFG_GLOBAL_TCPDUMP_SUPPORT              1
#define CFG_GLOBAL_SOCAT_SUPPORT                0
#define CFG_GLOBAL_STRACE_SUPPORT               0
#define CFG_GLOBAL_NTP_SUPPORT                  0
#define CFG_GLOBAL_ETHTOOL_SUPPORT              0
#define CFG_GLOBAL_LIBRT_SUPPORT                1
#define CFG_GLOBAL_OPENSSL_SUPPORT   1
#define CFG_GLOBAL_SROMPROG_SUPPORT   0
#define CFG_GLOBAL_WLDRIVER_SUPPORT   0
#define CFG_GLOBAL_DHD_SUPPORT   1
#define CFG_GLOBAL_TOOLCHAIN_VERSION            "buildroot-20080513"

#endif /* _CFG_GLOBAL_H_ */
