#!/system/bin/sh
#
# Print Merruk Technology Startup Informations
#
MT="log -p i -t cm"

$MT "   ###################################################################################    ";
$MT "   Welcome to Android : `getprop ro.build.version.release` / `getprop ro.product.manufacturer`-`getprop ro.build.display.id`   ";
$MT "   ###################################################################################    ";

$MT "   ";
$MT "    ,AHHM##AH#MM@MA###@#BAAA&&&AB###@M5. rA9X2222222222222222222222222222222222222229:   2h22222222Xr      ";
$MT "    @@@@@@#@@X:,3@@@5s2#@@@@@@@@@B2rsG@@# r@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@i   @@@@@@@@@@@@;     ";
$MT "   :@@H    @.    .;      A@@@@@;       :@@  #MHHA2XXM#2sS9M32XA@XsSXMG2XXHMHHHX2X9MB@r   H@##3X2i3BB@9     ";
$MT "   .@@:   r@              h@#@    :S:    @@ .#&&h        .#         #,   iMhhH    AH@;   H@i    .X&&MM     ";
$MT "   .@@    3@&@.    s@@.    @@r   &@@@A   5@i 3H&A    .X2;A#     5X;9@:   2MhhM    HH@;   2.   ;B#AhhH#     ";
$MT "   .@@    H@@@;   .@@@@    M@    2Xi25   .@@ :#AB    @@@#H#    #@@#B#;   X#hG#.   BH@;       r@@AG9hA@.    ";
$MT "   .@@    H@@@:    @@@@    B@             @@ .#H#   ,@MAGA#.   @#AG&#;   h@&H@.   MH@;    r   .#MGhhA#.    ";
$MT "   .@@    A@#@:    @@@@    #@    ,. ..,, :@@ ,#H#   .#Ahh&@.   #HhhG#s   :BHAr    MH@;   #@#    h#&GA#.    ";
$MT "   .@@    9@#@:    @@@M    @@,   #@@@@@@@@@# 5@@@   ,@#BB#@,   @#BBM@@;      .:   @@@s   @@@@:   S#M#@.    ";
$MT "   .@@,   i@#@;    @@@&    @@B    ;9BHhri@@: ,,:;,.. :,..,;,.  :..,.:rs:    .ir...,,::., :::rr.   .,,;     ";
$MT "   .@@5   :@@@;    @@@i   ;@@@3          @3 rs:.,,rrr,::;:;rs5;;;:,;;;i3S2hir;r9S;;;rrisrrr:;;SS;ir.r;     ";
$MT "    @@@.   @@@r    @@@.   #@@@@@r       ;s r@@@@&,@@3,&@;S@@H@:i@S,@SrXHs#s2@@iSM.@@;G@@;2r5@#i@Gr5A@9     ";
$MT "    2@@@@@#@@@@9AXA@@@@@@@@@@@@@@@@@@@@M: A@@##@As@@&sA#A2&H&@i9@As@XA@Gs#&2HB9HM;HH3XHBXMA2HAs#@i5@@      ";
$MT "   ";

exit 0
