##############################################################################
# MakeFile for the kernel Sensor device drivers
##############################################################################

# Object files in subdirectories

obj-$(CONFIG_J4FS)		+= j4fs/
obj-$(CONFIG_VIBETONZ)		+= vibetonz/
